export const data = [
    {
        game_id: 0,
        id: 1977,
        created_at: 1363530642,
        first_release_date: 1364342400,
        genres: ["Role-playing (RPG)", "Hack and slash/Beat 'em up"],
        name: "Scarlet Blade",
        platforms: ["PC (Microsoft Windows)"],
        screenshots: [
            "images.igdb.com/igdb/image/upload/t_thumb/gosapirsvvmeeckxlhri.jpg",
            "images.igdb.com/igdb/image/upload/t_thumb/kfc7kcoxccaeptbddjf5.jpg",
            "images.igdb.com/igdb/image/upload/t_thumb/dmgoq5kphw0usm4hjtwk.jpg",
            "images.igdb.com/igdb/image/upload/t_thumb/d08wblmupcaqni7kjc7x.jpg",
            "images.igdb.com/igdb/image/upload/t_thumb/ixdbfbyscjv6ipg1hmbr.jpg",
        ],
        summary: "Free-to-play MMORPG developed by LivePlex and published by Aeria Games. It is somewhat infamous for its cast of heavily-sexualized female characters.",
        url: "https://www.igdb.com/games/scarlet-blade",
    },
    {
        game_id: 1,
        id: 566,
        created_at: 1317722150,
        first_release_date: 1245110400,
        genres: ["Wii", "Adventure"],
        name: "Ghostbusters: The Video Game",
        platforms: ["Wii", "PC (Microsoft Windows)", "PlayStation 2", "PlayStation 3", "Xbox 360", "PlayStation Portable"],
        screenshots: [
            "images.igdb.com/igdb/image/upload/t_thumb/x251yhid8flt8yerxmvw.jpg",
            "images.igdb.com/igdb/image/upload/t_thumb/lmeilwtenumwur9pdzq8.jpg",
            "images.igdb.com/igdb/image/upload/t_thumb/o0ymjxruggmd8zpkvdfi.jpg",
            "images.igdb.com/igdb/image/upload/t_thumb/fd8oabxuojzix3sgoucb.jpg",
            "images.igdb.com/igdb/image/upload/t_thumb/qwo4cc8ozc8c3jnfyx8j.jpg",
        ],
        summary: "The Ghostbusters are back for an all new adventure. With Manhattan overrun again by supernatural creatures, gamers take the role of a new recruit joining the famous Ghostbusters team. Equipped with a variety of unique equipment and gadgets, players hunt, fight and wrangle a wide range of ghosts in an all-new battle to save New York City from its latest paranormal plague. \n \nDelivering a special gaming experience to the tremendous Ghostbusters fan base around the world, Ghostbusters: The Video Game features the original cast from Columbia Pictures' classic Ghostbusters films, including Bill Murray, Dan Aykroyd, Harold Ramis and Ernie Hudson - together again for the first time in over 20 years. Supporting the original Ghostbusters crew are the talents of Annie Potts, Brian Doyle Murray and William Atherton. \n \nLike the films before it, Ghostbusters: The Video Game is all-new classic adventure with Dan Aykroyd and Harold Ramis returning to the helm to script and create a new storyline that leads gamers through the trials and tribulations of the world's leading paranormal ghost busting team. Players experience a variety of frightening new ghosts, even some based on ideas from Aykroyd and Ramis that never made it into the original feature films.",
        url: "https://www.igdb.com/games/ghostbusters-the-video-game",
    },
    {
        game_id: 2,
        id: 563,
        created_at: 1317720769,
        first_release_date: 1247788800,
        genres: ["Role-playing (RPG)", "Turn-based strategy (TBS)"],
        name: "Aion",
        platforms: ["PC (Microsoft Windows)"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/aswskykwdkzsjmsodv7n.jpg"],
        summary: "A massively multiplayer online role-playing game released by NCSOFT. The game combines PvP and PvE in a fantasy game environment.",
        url: "https://www.igdb.com/games/aion",
    },
    {
        game_id: 3,
        id: 3013,
        created_at: 1381742013,
        first_release_date: 1373328000,
        genres: ["Wii", "Role-playing (RPG)", "Adventure"],
        name: "Fire Fall",
        platforms: ["PC (Microsoft Windows)"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/dbpko8jsbkbdcpiy0wkj.jpg", "images.igdb.com/igdb/image/upload/t_thumb/r31cq5fh9b14zk3l3mnc.jpg", "images.igdb.com/igdb/image/upload/t_thumb/hslpbqjogil19ka10q5z.jpg"],
        summary: "Firefall is a massively multiplayer online team-based action shooter role-playing computer game from Red 5 Studios, a studio founded by Mark Kern. It is currently in its open beta stage and it will attempt to mix elements from the MMORPG and MMOFPS genres when it is released.  \n \nThis game should not be confused with the Macintosh game from Pangea Software that was rereleased as shareware on June 13 in 2000.",
        url: "https://www.igdb.com/games/firefall",
    },
    {
        game_id: 4,
        id: 8428,
        created_at: 1420163110,
        first_release_date: 1400198400,
        genres: ["Role-playing (RPG)", "Adventure", "Indie"],
        name: "Dark Scavenger",
        platforms: ["PC (Microsoft Windows)"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/e5nng8cnxzrhl4lsro3v.jpg", "images.igdb.com/igdb/image/upload/t_thumb/uvcp2bryd7jbryy7viqe.jpg", "images.igdb.com/igdb/image/upload/t_thumb/vf4z4l314eqnjalg2rlx.jpg"],
        summary: "Dark Scavenger is a bizarre point-and-click RPG adventure with a focus on exploration, gaining loot, and meaningful choices. Filling the role of a powerful space traveler, you find yourself stranded on a mysterious alien planet. Will you save the world or just yourself?",
        url: "https://www.igdb.com/games/dark-scavenger",
    },
    {
        game_id: 5,
        id: 9724,
        created_at: 1428949369,
        first_release_date: 1373328000,
        genres: ["Role-playing (RPG)", "Tactical", "Indie", "Arcade"],
        name: "Ring Runner: Flight of the Sages",
        platforms: ["PC (Microsoft Windows)"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/zp60g52gwab1glfjiafc.jpg", "images.igdb.com/igdb/image/upload/t_thumb/npe0c8mphnlmp9elxqko.jpg", "images.igdb.com/igdb/image/upload/t_thumb/tohhqqg1iyx8brbprits.jpg"],
        summary: "Ring Runner combines the fast-paced action of space combat with the rich story and skill variety of an RPG. Trek across the universe in a 30 hour long story-driven campaign based on a companion Sci Fi novel, or challenge 6 scenarios alone, cooperatively, or competitively through local or online multiplayer.",
        url: "https://www.igdb.com/games/ring-runner-flight-of-the-sages",
    },
    {
        game_id: 6,
        id: 9337,
        created_at: 1427910652,
        first_release_date: 1409011200,
        genres: ["Simulator", "Adventure", "Indie"],
        name: "World of Diving",
        platforms: ["PC (Microsoft Windows)"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/qwvrirvpgkpusfgf6szv.jpg", "images.igdb.com/igdb/image/upload/t_thumb/x5ppvjjchqzvyrozruje.jpg", "images.igdb.com/igdb/image/upload/t_thumb/iyen8ynibmsdazkbi6fy.jpg"],
        summary: "World of Diving is the Oculus Rift-enabled online diving game that brings you an exhilarating multiplayer diving adventure, all without getting wet. access the game via Early Access and start playing straight away!",
        url: "https://www.igdb.com/games/world-of-diving",
    },
    {
        game_id: 7,
        id: 33284,
        created_at: 1495670400,
        first_release_date: 1457740800,
        genres: ["Indie"],
        name: "One way to exit",
        platforms: ["PC (Microsoft Windows)"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/ffow63l4ywfkyd0gmsez.jpg", "images.igdb.com/igdb/image/upload/t_thumb/gpkeqan21zroszd2nvsl.jpg", "images.igdb.com/igdb/image/upload/t_thumb/behvwwk3nlhfvlhcfcm3.jpg"],
        summary: "Move forward or backward in search of an exit, but remember, if you started moving you can not stop, and in any case, do not touch the walls, otherwise you have to start all over again.",
        url: "https://www.igdb.com/games/one-way-to-exit",
    },
    {
        game_id: 8,
        id: 35281,
        created_at: 1495756800,
        first_release_date: 1431043200,
        genres: ["Role-playing (RPG)", "Adventure", "Indie"],
        name: "Valiant: Resurrection",
        platforms: ["PC (Microsoft Windows)"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/yqoz89hfreaj2bki1xef.jpg", "images.igdb.com/igdb/image/upload/t_thumb/lpgpa2q4y5n1bxvtua7g.jpg", "images.igdb.com/igdb/image/upload/t_thumb/qzrrsfzmntxpdc9fhqfq.jpg"],
        summary: "Explore the lands of Sirenus Bay, God’s Garden, Whitebleak, Fort Ember, God Snare, and the mysterious Immortal’s Abyss. Are you brave enough for this adventure?",
        url: "https://www.igdb.com/games/valiant-resurrection",
    },
    {
        game_id: 9,
        id: 33319,
        created_at: 1495670400,
        first_release_date: 1499731200,
        genres: ["Simulator", "Adventure", "Indie"],
        name: "Ariel",
        platforms: ["PC (Microsoft Windows)", "Mac"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/pox6w8cqg5hhfducn0dm.jpg", "images.igdb.com/igdb/image/upload/t_thumb/ajcuph6ztssldzxs9una.jpg", "images.igdb.com/igdb/image/upload/t_thumb/wjdpzipd73jzstob1uug.jpg"],
        summary: "Intense survival experience based on a Sci-Fi, space terror script. Unravel the story of Ferdinand Ludec as he attempts to escape his fortune. Partially procedural world along with different endings to the story. Hunger, avoiding insanity and extreme weather will only be some of the threats to face. \n \nAriel - There is no way out -",
        url: "https://www.igdb.com/games/ariel",
    },
    {
        game_id: 10,
        id: 33160,
        created_at: 1495670400,
        first_release_date: 1461715200,
        genres: ["Role-playing (RPG)", "Adventure", "Indie"],
        name: "The Orphan Dreams",
        platforms: ["PC (Microsoft Windows)"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/ughbe298qbgz2jkn8dcl.jpg", "images.igdb.com/igdb/image/upload/t_thumb/lnzi7tpqkvdb6paypbve.jpg", "images.igdb.com/igdb/image/upload/t_thumb/skpqkmpacqqxvnxxkpzf.jpg"],
        summary: "The Orphan Dreams is a permadeath adventure game combined with RPG elements. Step into the universe of The Orphan, who in his dream finds a letter from his own mother he has never seen before.",
        url: "https://www.igdb.com/games/the-orphan-dreams",
    },
    {
        game_id: 11,
        id: 34320,
        created_at: 1495756800,
        first_release_date: 1461801600,
        genres: ["Simulator", "Sport", "Indie"],
        name: "Pro Gamer Manager",
        platforms: ["PC (Microsoft Windows)"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/shjmhwaji9hu6odl03h1.jpg", "images.igdb.com/igdb/image/upload/t_thumb/mp9kwfyqtau7ts2mgbfb.jpg", "images.igdb.com/igdb/image/upload/t_thumb/ouu8plelp8xt9xcodat2.jpg"],
        summary: "Compete for stardom in this Esport management tycoon.",
        url: "https://www.igdb.com/games/pro-gamer-manager",
    },
    {
        game_id: 12,
        id: 34309,
        created_at: 1495795570,
        first_release_date: 1454025600,
        genres: ["Indie"],
        name: "Perraw - FPS Clone War",
        platforms: ["PC (Microsoft Windows)"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/dcs03jqnid5xyk8iyrti.jpg", "images.igdb.com/igdb/image/upload/t_thumb/z84fxzjon9hbiqwwuubv.jpg", "images.igdb.com/igdb/image/upload/t_thumb/fdxe03mtinjx3sdejjuw.jpg"],
        summary: "Perraw is a FPS multiplayer/Tower Defense placed in an futuristic environment Developed in free time as a hobby. WARNING: THIS GAME IS EARLY ACCESS ALPHA.",
        url: "https://www.igdb.com/games/perraw-fps-clone-war",
    },
    {
        game_id: 13,
        id: 74857,
        created_at: 1508457600,
        first_release_date: 1512086400,
        genres: ["Platform", "Puzzle", "Role-playing (RPG)", "Adventure", "Indie"],
        name: "Transcend",
        platforms: ["PC (Microsoft Windows)"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/lrgn3fa3bbzaglnbf3mi.jpg", "images.igdb.com/igdb/image/upload/t_thumb/vfbyyaoqy3qbwreaynjz.jpg", "images.igdb.com/igdb/image/upload/t_thumb/wwxaqvlulmgbx2o8vzqy.jpg"],
        summary: "A puzzle platformer in which you transcend life and death to reach your goals.",
        url: "https://www.igdb.com/games/transcend",
    },
    {
        game_id: 14,
        id: 78193,
        created_at: 1513468800,
        first_release_date: 1041292800,
        genres: ["Racing"],
        name: "Test Drive",
        platforms: ["PC (Microsoft Windows)", "PlayStation 2", "Xbox"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/sc75up.jpg", "images.igdb.com/igdb/image/upload/t_thumb/sc75uq.jpg", "images.igdb.com/igdb/image/upload/t_thumb/sc75ur.jpg"],
        summary:"Test Drive is a racing game developed by Pitbull Syndicate. In Test Drive, you play as Dennis Black, a street racer who is contacted by a wheelchair-bound man and hired to race in his place in a series of underground street races known as \"test drives\". \n \nThis edition of Test Drive has some improvements over it's predecessor, Test Drive 6. This time around there is a story driven mode, called \"The Underground.\" You take the role of Dennis Black, an independent street racer who improves his standing in the underground street racing world with the help of a mysterious benefactor.",
        url: "https://www.igdb.com/games/test-drive--1",
    },
    {
        game_id: 15,
        id: 74958,
        created_at: 1508976000,
        first_release_date: 1509494400,
        genres: ["Simulator", "Strategy"],
        name: "ALVAROK",
        platforms: ["PC (Microsoft Windows)"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/wi3wkdfvqfkms4eqcr2y.jpg", "images.igdb.com/igdb/image/upload/t_thumb/srwhkpmyh9ribzsu6y7n.jpg", "images.igdb.com/igdb/image/upload/t_thumb/mzfrsvchncmyfwxediqc.jpg"],
        summary: "Japanese Indie developer StudioGIW is back with ALVAROK, a fun and easy-to-play Tactical Defense game. Play locally with friends or hone your skills against the computer with its built-in deep learning AI system. Adapt and strategize, utilize your various troops to defend and attack simultaneously.",
        url: "https://www.igdb.com/games/alvarok",
    },
    {
        game_id: 16,
        id: 75076,
        created_at: 1509098229,
        first_release_date: 1538611200,
        genres: ["Racing", "Sport", "Indie", "Arcade"],
        name: "Party Crashers",
        platforms: ["PC (Microsoft Windows)", "PlayStation 4", "Nintendo Switch"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/iifhzkrmhesfbsl6jpzb.jpg", "images.igdb.com/igdb/image/upload/t_thumb/sqcp9y1hm58jivdcetds.jpg", "images.igdb.com/igdb/image/upload/t_thumb/jxmvrbvxfpejyca860zd.jpg"],
        summary:"Party Crashers is an arcade combat racer, featuring fast-paced last-car-standing gameplay, with a huge array of customisation options to allow players to create your own style of play.\n\nBy default, players race on a single screen and players that fall too far behind or fall of the track are eliminated. The game is made more hectic and rounds are kept short by weapons scattered around the track that create ways for players to eliminate each other. Points are awarded for staying alive as long as possible.\n\nFollowing in the footsteps of Party Golf, the game has a deep customisation system that allows everything about \"normal\" gameplay to be changed so players can create whatever style of gameplay they like the most!",
        url: "https://www.igdb.com/games/party-crashers",
    },
    {
        game_id: 17,
        id: 74426,
        created_at: 1508117337,
        first_release_date: 978220800,
        genres: ["Platform"],
        name: "The Emperor's New Groove",
        platforms: ["Game Boy Color"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/sc9kny.jpg", "images.igdb.com/igdb/image/upload/t_thumb/exalhrvzsqtdwg39ttwk.jpg", "images.igdb.com/igdb/image/upload/t_thumb/fh7pqmeogwp9nllj27cx.jpg"],
        summary: "The Emperor's New Groove is a video game based on the 2000 Disney film of the same name, developed by Sandbox Studios for the Game Boy Color.",
        url: "https://www.igdb.com/games/the-emperors-new-groove--1",
    },
    {
        game_id: 18,
        id: 74369,
        created_at: 1507813635,
        first_release_date: 1517443200,
        genres: ["Simulator", "Strategy", "Indie"],
        name: "Startup Freak",
        platforms: ["PC (Microsoft Windows)"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/d9ocripwckm3rldaxijx.jpg", "images.igdb.com/igdb/image/upload/t_thumb/zx9wrgwml5qgk5vd3udm.jpg", "images.igdb.com/igdb/image/upload/t_thumb/oilrila2luf9poyrtxh8.jpg"],
        summary: "In Startup Freak you take the role of a budding entrepreneur, and grow your very own software startup from humble beginnings to a multi-million dollar company. Along the way you will have to overcome countless challenges. But the ultimate question you must answer: are you a Startup Freak?",
        url: "https://www.igdb.com/games/startup-freak",
    },
    {
        game_id: 19,
        id: 79587,
        created_at: 1514505600,
        first_release_date: 539136000,
        genres: ["Platform", "Strategy", "Arcade"],
        name: "Subnodule",
        platforms: ["Mac"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/n5lfib14zsif7iojl01c.jpg", "images.igdb.com/igdb/image/upload/t_thumb/xrl6jy3fyycvti0a6wzk.jpg", "images.igdb.com/igdb/image/upload/t_thumb/bda3lj2q05jhxd851pit.jpg"],
        summary: "You control a submarine in hostile waters. Sharing the deep sea with you are several dangerous creatures such as jellyfish, eels, sharks and the mysterious X-Sub. Destroy everything to reach the next level. This game has intermissions as well.",
        url: "https://www.igdb.com/games/subnodule",
    },
    {
        game_id: 20,
        id: 86080,
        created_at: 1517529600,
        first_release_date: 1451520000,
        genres: ["Music"],
        name: "Sing Star: Frozen",
        platforms: ["PlayStation 3", "PlayStation 4"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/sc7fxs.jpg", "images.igdb.com/igdb/image/upload/t_thumb/sc7fxr.jpg", "images.igdb.com/igdb/image/upload/t_thumb/sc7fxq.jpg"],
        summary:"SingStar: Frozen is a karaoke game based on the animated movie Frozen. Except for the song Let It Go from Demi Lovato, which is the available in all language version, the other nine songs are translated and taken directly from the movie (including dialogue). There are no changes to the gameplay formula: player(s) sing into a microphone and the game gives points based on the performance. It is only rated if the correct not is hit at the correct time; the sung words or octave does not play into the result.",
        url: "https://www.igdb.com/games/singstar-frozen",
    },
    {
        game_id: 21,
        id: 93800,
        created_at: 1521331200,
        first_release_date: 1522281600,
        genres: ["Simulator", "Adventure", "Indie"],
        name: "Temptation",
        platforms: ["PC (Microsoft Windows)"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/cmd5yfdl9kksjnnyoyuj.jpg", "images.igdb.com/igdb/image/upload/t_thumb/sngfz6kmc9ofedjpfysq.jpg", "images.igdb.com/igdb/image/upload/t_thumb/biwo0zlfx1j1hayewus9.jpg"],
        summary: "Temptation - a game about a medieval priest who is suddenly possessed by a demon. Your goal is to perform an unusual ritual of exorcism to banish the demon from himself!",
        url: "https://www.igdb.com/games/temptation",
    },
    {
        game_id: 22,
        id: 81357,
        created_at: 1515801600,
        first_release_date: 1378252800,
        genres: ["Simulator"],
        name: "Farming Simulator",
        platforms: ["PlayStation 3"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/us23glclxamzogyo48so.jpg", "images.igdb.com/igdb/image/upload/t_thumb/lyhbt09yull4mksdiw6c.jpg", "images.igdb.com/igdb/image/upload/t_thumb/q3fwaeqguzmhsgcyx6dq.jpg"],
        summary: "Discover a wide, agricultural scenery with fields, roads, your farm as well as a small village. Cultivate your fields with various three dimensional vehicles found in your generous fleet- modeled after original machines and vehicles by prestigious manufacturers.",
        url: "https://www.igdb.com/games/farming-simulator",
    },
    {
        game_id: 23,
        id: 94804,
        created_at: 1521417600,
        first_release_date: 1592956800,
        genres: ["Simulator", "Strategy", "Indie"],
        name: "Space Station Continuum",
        platforms: ["PC (Microsoft Windows)"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/sxmocemxh7fdc8szw4y8.jpg", "images.igdb.com/igdb/image/upload/t_thumb/brcuacvrlpxtts5opltp.jpg", "images.igdb.com/igdb/image/upload/t_thumb/hrrtethoeszgwnaryqvi.jpg"],
        summary: "Space Station Continuum is a building & management sim inspired by the past, present, and future of humans in space.",
        url: "https://www.igdb.com/games/space-station-continuum",
    },
    {
        game_id: 24,
        id: 80867,
        created_at: 1515369600,
        first_release_date: 725760000,
        genres: ["Shooter", "Arcade"],
        name: "Night Raid",
        platforms: ["PC DOS"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/sc75co.jpg", "images.igdb.com/igdb/image/upload/t_thumb/sc75cn.jpg", "images.igdb.com/igdb/image/upload/t_thumb/sc75cp.jpg"],
        summary:"Remake of 1982's Paratrooper. \n \nThe player controls a gun turret at the bottom of the screen. The turret can swivel to cover a large area of the screen, but cannot move from its base. Helicopters fly across the screen at varying heights, dropping paratroopers. The gun may fire multiple shots at once, and the shots may destroy helicopters or shoot paratroopers. Paratroopers may be disintegrated by a direct hit, or their parachutes may be shot, in which case they will plummet to earth (splattering and dying, killing any paratrooper onto whom they fall). Periodically, jets may fly by and drop bombs; the jets and bombs may be shot as well.",
        url: "https://www.igdb.com/games/night-raid--1",
    },
    {
        game_id: 25,
        id: 91231,
        created_at: 1521072000,
        first_release_date: 1489104000,
        genres: ["Simulator"],
        name: "Stickman Dismounting",
        platforms: ["iOS"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/ljj41yqadl5sxhnq3h1o.jpg", "images.igdb.com/igdb/image/upload/t_thumb/myh8sbkte9r7i1oxnmow.jpg", "images.igdb.com/igdb/image/upload/t_thumb/boy4wxbuney7amnrblrs.jpg"],
        summary:"Perform amazing stunts, crash into walls, break bones, destroy vehicles and have the fun!\n\nFEATURES:\n- unique active ragdoll physics system\n- crunchy sound effects\n- multiple levels\n- multiple vehicles\n- multiple props for level customization\n- replay system with saving and sharing abilities\n\nDo not attempt game actions in real life.",
        url: "https://www.igdb.com/games/stickman-dismounting",
    },
    {
        game_id: 26,
        id: 94567,
        created_at: 1521408228,
        first_release_date: 1131580800,
        genres: ["Simulator", 3],
        name: "PC Fútbol 2006",
        platforms: ["PC (Microsoft Windows)"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/sc935n.jpg", "images.igdb.com/igdb/image/upload/t_thumb/sc935m.jpg", "images.igdb.com/igdb/image/upload/t_thumb/sc935l.jpg"],
        summary: "PC Fútbol is a football managerial game with different game styles. You can take an equip from the beginning or play the manager mode waiting and selecting offers from the equips. \n \nYou can trade and train players, make strategics, build the stadium and services, select sponsors, sell merchandising and lot of more.",
        url: "https://www.igdb.com/games/pc-futbol-2006",
    },
    {
        game_id: 27,
        id: 90228,
        created_at: 1520640000,
        first_release_date: 1367193600,
        genres: ["Adventure", "Indie"],
        name: "Skumring",
        platforms: ["PC (Microsoft Windows)"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/twpkqd6awodfg3ialsyl.jpg", "images.igdb.com/igdb/image/upload/t_thumb/i9fxn4fcyhlk9sqrmhzf.jpg", "images.igdb.com/igdb/image/upload/t_thumb/b8vwddfkr6zrwohzfzle.jpg"],
        summary:"Port Horizon 1951. A city on the verge of collapse. Moral collapse. Crime. Corruption. Greed... Money. Private eye Cooper Chutney thought he was the exception. When a beautiful dame in distress enters his office he is ready to show that someone still cares about something in this wretched town. But as he soon will learn everything can change during a cold Port Horizon night... Skumringª features 30+ locations, 15+ characters and 40+ inventory items. It will also feature a varied soundtrack, consisting of traditional jazz and original interpretations of classical music.",
        url: "https://www.igdb.com/games/skumring",
    },
    {
        game_id: 28,
        id: 146815,
        created_at: 1620325446,
        first_release_date: 1230681600,
        genres: ["Puzzle"],
        name: "Parking Lot Maze",
        platforms: ["PC (Microsoft Windows)"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/sc9gxx.jpg", "images.igdb.com/igdb/image/upload/t_thumb/sc9gxw.jpg", "images.igdb.com/igdb/image/upload/t_thumb/sc9gxv.jpg"],
        summary: "Parking Lot Maze is a puzzle game where as a parking lot manager, you need to free cars from gridlock before the stress level hits the roof.",
        url: "https://www.igdb.com/games/parking-lot-maze",
    },
    {
        game_id: 29,
        id: 148226,
        created_at: 1621464692,
        first_release_date: 1621468800,
        genres: ["Adventure", "Indie"],
        name: "If It Please the Court",
        platforms: ["Linux", "PC (Microsoft Windows)", "Mac"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/sc9o8w.jpg", "images.igdb.com/igdb/image/upload/t_thumb/sc9o8x.jpg", "images.igdb.com/igdb/image/upload/t_thumb/sc9o8y.jpg"],
        summary: "A text-based interactive lesbian romance novel set in 1700's France. Gather intel, or gamble on love in Versailles! Who will catch your eye: a spymistress, a poet, or a traitor to the king?",
        url: "https://www.igdb.com/games/if-it-please-the-court",
    },
    {
        game_id: 30,
        id: 132734,
        created_at: 1587643768,
        first_release_date: 1640908800,
        genres: ["Strategy", "Indie"],
        name: "Iron Vulture",
        platforms: ["PC (Microsoft Windows)"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/sc8t1b.jpg", "images.igdb.com/igdb/image/upload/t_thumb/sc8t1c.jpg", "images.igdb.com/igdb/image/upload/t_thumb/sc8t1e.jpg"],
        summary: "Iron Vulture is a real-time strategy line defender. You can command six soldiers in real-time combat, move them across lanes, and use their abilities to eliminate wave after wave of mutated creatures.",
        url: "https://www.igdb.com/games/iron-vulture",
    },
    {
        game_id: 31,
        id: 143104,
        created_at: 1612324563,
        first_release_date: 1611273600,
        genres: ["Indie"],
        name: "i am still here.",
        platforms: ["Web browser"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/sc90ix.jpg"],
        summary: "A short experience about ghosts and places and people, set in the first days/weeks after the lockdown ended in Melbourne.",
        url: "https://www.igdb.com/games/i-am-still-here",
    },
    {
        game_id: 32,
        id: 105595,
        created_at: 1532106731,
        first_release_date: 1532649600,
        genres: ["Indie"],
        name: "Magic Mechsuit Akane",
        platforms: ["PC (Microsoft Windows)"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/amnz8ix1w57zhcou4ftm.jpg", "images.igdb.com/igdb/image/upload/t_thumb/nzulu2ckee51i9y6jjc3.jpg", "images.igdb.com/igdb/image/upload/t_thumb/wdmm3ctazrdx81isv1eg.jpg"],
        summary:"Magic MechSuit Akane  \n\"Mechanism-replacement action shooting\" - start  \nCombat action to create a powered suit by combining up to 16 parts such as generators and radiators!  \nIn addition to being able to play offline with a preset machine or self-made machine with 1 VS1, you can also play online with up to 3 VS 3. \nDefeat your opponent with a metal called MechSuit and armor that magic got together!",
        url: "https://www.igdb.com/games/magic-mechsuit-akane",
    },
    {
        game_id: 33,
        id: 122050,
        created_at: 1566892004,
        first_release_date: 1640908800,
        genres: ["Platform", "Puzzle", "Adventure", "Indie"],
        name: "A Juggler's Tale",
        platforms: ["PC (Microsoft Windows)", "PlayStation 4", "Xbox One", "Nintendo Switch"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/sc6wq3.jpg", "images.igdb.com/igdb/image/upload/t_thumb/sc6wq5.jpg", "images.igdb.com/igdb/image/upload/t_thumb/sc6wq4.jpg"],
        summary: "Lead Abby the string puppet through a bruised, but beautiful world in this poetic 3D adventure. Solve riddles, evade traps, and shake off pursuers on your way to find freedom. Can Abby take control of her own fate and make a difference with all the strings attached?",
        url: "https://www.igdb.com/games/a-jugglers-tale",
    },
    {
        game_id: 34,
        id: 130974,
        created_at: 1582462146,
        first_release_date: 1575590400,
        genres: ["Strategy", "Indie"],
        name: "Dodge If you Can!",
        platforms: ["PC (Microsoft Windows)"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/sc85wc.jpg", "images.igdb.com/igdb/image/upload/t_thumb/sc85we.jpg", "images.igdb.com/igdb/image/upload/t_thumb/sc85wf.jpg"],
        summary: "Dodge If you Can! A simple game where you will either emerge as a Master of strategy, or become a statistic. Will your strategy and wits prevail among the storm of bullets? Will you go down as a legend? Only you can decide. Now - Dodge, If you Can!",
        url: "https://www.igdb.com/games/dodge-if-you-can",
    },
    {
        game_id: 35,
        id: 108661,
        created_at: 1536219841,
        first_release_date: 1537142400,
        genres: ["Adventure", "Indie"],
        name: "Escape from the Princess",
        platforms: ["PC (Microsoft Windows)"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/kq3jon9oz2stetpbhi5j.jpg", "images.igdb.com/igdb/image/upload/t_thumb/jkx6biyilxhlf04zuxdd.jpg", "images.igdb.com/igdb/image/upload/t_thumb/zyatdy7donfliviw4tbn.jpg"],
        summary: "Rosetta dreams of becoming a magician, but she isn't cut out for it. Fate brings her together with a mysterious witch, who is pursued by the princess herself. The witch promises to make Rosetta a magician in return for her help. But Rose falls in love with a witch who is clearly hiding something.",
        url: "https://www.igdb.com/games/escape-from-the-princess",
    },
];
