export const data = [
    {
        game_id: 0,
        id: 1977,
        created_at: 1363530642,
        first_release_date: 1364342400,
        genres: ["Role-playing (RPG)", "Hack and slash/Beat 'em up"],
        name: "ScarletBlade",
        platforms: ["PC (Microsoft Windows)"],
        screenshots: [
            "images.igdb.com/igdb/image/upload/t_thumb/gosapirsvvmeeckxlhri.jpg",
            "images.igdb.com/igdb/image/upload/t_thumb/kfc7kcoxccaeptbddjf5.jpg",
            "images.igdb.com/igdb/image/upload/t_thumb/dmgoq5kphw0usm4hjtwk.jpg",
            "images.igdb.com/igdb/image/upload/t_thumb/d08wblmupcaqni7kjc7x.jpg",
            "images.igdb.com/igdb/image/upload/t_thumb/ixdbfbyscjv6ipg1hmbr.jpg",
        ],
        summary: "Free-to-playMMORPGdevelopedbyLivePlexandpublishedbyAeriaGames.Itissomewhatinfamousforitscastofheavily-sexualizedfemalecharacters.",
        url: "https://www.igdb.com/games/scarlet-blade",
    },
    {
        game_id: 1,
        id: 566,
        created_at: 1317722150,
        first_release_date: 1245110400,
        genres: ["Wii", "Adventure"],
        name: "Ghostbusters:TheVideoGame",
        platforms: ["Wii", "PC (Microsoft Windows)", "PlayStation 2", "PlayStation 3", "Xbox 360", "PlayStation Portable"],
        screenshots: [
            "images.igdb.com/igdb/image/upload/t_thumb/x251yhid8flt8yerxmvw.jpg",
            "images.igdb.com/igdb/image/upload/t_thumb/lmeilwtenumwur9pdzq8.jpg",
            "images.igdb.com/igdb/image/upload/t_thumb/o0ymjxruggmd8zpkvdfi.jpg",
            "images.igdb.com/igdb/image/upload/t_thumb/fd8oabxuojzix3sgoucb.jpg",
            "images.igdb.com/igdb/image/upload/t_thumb/qwo4cc8ozc8c3jnfyx8j.jpg",
        ],
        summary:
            "TheGhostbustersarebackforanallnewadventure.WithManhattanoverrunagainbysupernaturalcreatures,gamerstaketheroleofanewrecruitjoiningthefamousGhostbustersteam.Equippedwithavarietyofuniqueequipmentandgadgets,playershunt,fightandwrangleawiderangeofghostsinanall-newbattletosaveNewYorkCityfromitslatestparanormalplague.\n\nDeliveringaspecialgamingexperiencetothetremendousGhostbustersfanbasearoundtheworld,Ghostbusters:TheVideoGamefeaturestheoriginalcastfromColumbiaPictures'classicGhostbustersfilms,includingBillMurray,DanAykroyd,HaroldRamisandErnieHudson-togetheragainforthefirsttimeinover20years.SupportingtheoriginalGhostbusterscrewarethetalentsofAnniePotts,BrianDoyleMurrayandWilliamAtherton.\n\nLikethefilmsbeforeit,Ghostbusters:TheVideoGameisall-newclassicadventurewithDanAykroydandHaroldRamisreturningtothehelmtoscriptandcreateanewstorylinethatleadsgamersthroughthetrialsandtribulationsoftheworld'sleadingparanormalghostbustingteam.Playersexperienceavarietyoffrighteningnewghosts,evensomebasedonideasfromAykroydandRamisthatnevermadeitintotheoriginalfeaturefilms.",
        url: "https://www.igdb.com/games/ghostbusters-the-video-game",
    },
    {
        game_id: 2,
        id: 563,
        created_at: 1317720769,
        first_release_date: 1247788800,
        genres: ["Role-playing (RPG)", "Turn-based strategy (TBS)"],
        name: "Aion",
        platforms: ["PC (Microsoft Windows)"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/aswskykwdkzsjmsodv7n.jpg"],
        summary: "Amassivelymultiplayeronlinerole-playinggamereleasedbyNCSOFT.ThegamecombinesPvPandPvEinafantasygameenvironment.",
        url: "https://www.igdb.com/games/aion",
    },
    {
        game_id: 3,
        id: 3013,
        created_at: 1381742013,
        first_release_date: 1373328000,
        genres: ["Wii", "Role-playing (RPG)", "Adventure"],
        name: "FireFall",
        platforms: ["PC (Microsoft Windows)"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/dbpko8jsbkbdcpiy0wkj.jpg", "images.igdb.com/igdb/image/upload/t_thumb/r31cq5fh9b14zk3l3mnc.jpg", "images.igdb.com/igdb/image/upload/t_thumb/hslpbqjogil19ka10q5z.jpg"],
        summary:
            "Firefallisamassivelymultiplayeronlineteam-basedactionshooterrole-playingcomputergamefromRed5Studios,astudiofoundedbyMarkKern.ItiscurrentlyinitsopenbetastageanditwillattempttomixelementsfromtheMMORPGandMMOFPSgenreswhenitisreleased.\n\nThisgameshouldnotbeconfusedwiththeMacintoshgamefromPangeaSoftwarethatwasrereleasedassharewareonJune13in2000.",
        url: "https://www.igdb.com/games/firefall",
    },
    {
        game_id: 4,
        id: 8428,
        created_at: 1420163110,
        first_release_date: 1400198400,
        genres: ["Role-playing (RPG)", "Adventure", "Indie"],
        name: "DarkScavenger",
        platforms: ["PC (Microsoft Windows)"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/e5nng8cnxzrhl4lsro3v.jpg", "images.igdb.com/igdb/image/upload/t_thumb/uvcp2bryd7jbryy7viqe.jpg", "images.igdb.com/igdb/image/upload/t_thumb/vf4z4l314eqnjalg2rlx.jpg"],
        summary: "DarkScavengerisabizarrepoint-and-clickRPGadventurewithafocusonexploration,gainingloot,andmeaningfulchoices.Fillingtheroleofapowerfulspacetraveler,youfindyourselfstrandedonamysteriousalienplanet.Willyousavetheworldorjustyourself?",
        url: "https://www.igdb.com/games/dark-scavenger",
    },
    {
        game_id: 5,
        id: 9724,
        created_at: 1428949369,
        first_release_date: 1373328000,
        genres: ["Role-playing (RPG)", "Tactical", "Indie", "Arcade"],
        name: "RingRunner:FlightoftheSages",
        platforms: ["PC (Microsoft Windows)"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/zp60g52gwab1glfjiafc.jpg", "images.igdb.com/igdb/image/upload/t_thumb/npe0c8mphnlmp9elxqko.jpg", "images.igdb.com/igdb/image/upload/t_thumb/tohhqqg1iyx8brbprits.jpg"],
        summary: "RingRunnercombinesthefast-pacedactionofspacecombatwiththerichstoryandskillvarietyofanRPG.Trekacrosstheuniverseina30hourlongstory-drivencampaignbasedonacompanionSciFinovel,orchallenge6scenariosalone,cooperatively,orcompetitivelythroughlocaloronlinemultiplayer.",
        url: "https://www.igdb.com/games/ring-runner-flight-of-the-sages",
    },
    {
        game_id: 6,
        id: 9337,
        created_at: 1427910652,
        first_release_date: 1409011200,
        genres: ["Simulator", "Adventure", "Indie"],
        name: "WorldofDiving",
        platforms: ["PC (Microsoft Windows)"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/qwvrirvpgkpusfgf6szv.jpg", "images.igdb.com/igdb/image/upload/t_thumb/x5ppvjjchqzvyrozruje.jpg", "images.igdb.com/igdb/image/upload/t_thumb/iyen8ynibmsdazkbi6fy.jpg"],
        summary: "WorldofDivingistheOculusRift-enabledonlinedivinggamethatbringsyouanexhilaratingmultiplayerdivingadventure,allwithoutgettingwet.accessthegameviaEarlyAccessandstartplayingstraightaway!",
        url: "https://www.igdb.com/games/world-of-diving",
    },
    {
        game_id: 7,
        id: 33284,
        created_at: 1495670400,
        first_release_date: 1457740800,
        genres: ["Indie"],
        name: "Onewaytoexit",
        platforms: ["PC (Microsoft Windows)"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/ffow63l4ywfkyd0gmsez.jpg", "images.igdb.com/igdb/image/upload/t_thumb/gpkeqan21zroszd2nvsl.jpg", "images.igdb.com/igdb/image/upload/t_thumb/behvwwk3nlhfvlhcfcm3.jpg"],
        summary: "Moveforwardorbackwardinsearchofanexit,butremember,ifyoustartedmovingyoucannotstop,andinanycase,donottouchthewalls,otherwiseyouhavetostartalloveragain.",
        url: "https://www.igdb.com/games/one-way-to-exit",
    },
    {
        game_id: 8,
        id: 35281,
        created_at: 1495756800,
        first_release_date: 1431043200,
        genres: ["Role-playing (RPG)", "Adventure", "Indie"],
        name: "Valiant:Resurrection",
        platforms: ["PC (Microsoft Windows)"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/yqoz89hfreaj2bki1xef.jpg", "images.igdb.com/igdb/image/upload/t_thumb/lpgpa2q4y5n1bxvtua7g.jpg", "images.igdb.com/igdb/image/upload/t_thumb/qzrrsfzmntxpdc9fhqfq.jpg"],
        summary: "ExplorethelandsofSirenusBay,God’sGarden,Whitebleak,FortEmber,GodSnare,andthemysteriousImmortal’sAbyss.Areyoubraveenoughforthisadventure?",
        url: "https://www.igdb.com/games/valiant-resurrection",
    },
    {
        game_id: 9,
        id: 33319,
        created_at: 1495670400,
        first_release_date: 1499731200,
        genres: ["Simulator", "Adventure", "Indie"],
        name: "Ariel",
        platforms: ["PC (Microsoft Windows)", "Mac"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/pox6w8cqg5hhfducn0dm.jpg", "images.igdb.com/igdb/image/upload/t_thumb/ajcuph6ztssldzxs9una.jpg", "images.igdb.com/igdb/image/upload/t_thumb/wjdpzipd73jzstob1uug.jpg"],
        summary: "IntensesurvivalexperiencebasedonaSci-Fi,spaceterrorscript.UnravelthestoryofFerdinandLudecasheattemptstoescapehisfortune.Partiallyproceduralworldalongwithdifferentendingstothestory.Hunger,avoidinginsanityandextremeweatherwillonlybesomeofthethreatstoface.\n\nAriel-Thereisnowayout-",
        url: "https://www.igdb.com/games/ariel",
    },
    {
        game_id: 10,
        id: 33160,
        created_at: 1495670400,
        first_release_date: 1461715200,
        genres: ["Role-playing (RPG)", "Adventure", "Indie"],
        name: "TheOrphanDreams",
        platforms: ["PC (Microsoft Windows)"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/ughbe298qbgz2jkn8dcl.jpg", "images.igdb.com/igdb/image/upload/t_thumb/lnzi7tpqkvdb6paypbve.jpg", "images.igdb.com/igdb/image/upload/t_thumb/skpqkmpacqqxvnxxkpzf.jpg"],
        summary: "TheOrphanDreamsisapermadeathadventuregamecombinedwithRPGelements.StepintotheuniverseofTheOrphan,whoinhisdreamfindsaletterfromhisownmotherhehasneverseenbefore.",
        url: "https://www.igdb.com/games/the-orphan-dreams",
    },
    {
        game_id: 11,
        id: 34320,
        created_at: 1495756800,
        first_release_date: 1461801600,
        genres: ["Simulator", "Sport", "Indie"],
        name: "ProGamerManager",
        platforms: ["PC (Microsoft Windows)"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/shjmhwaji9hu6odl03h1.jpg", "images.igdb.com/igdb/image/upload/t_thumb/mp9kwfyqtau7ts2mgbfb.jpg", "images.igdb.com/igdb/image/upload/t_thumb/ouu8plelp8xt9xcodat2.jpg"],
        summary: "CompeteforstardominthisEsportmanagementtycoon.",
        url: "https://www.igdb.com/games/pro-gamer-manager",
    },
    {
        game_id: 12,
        id: 34309,
        created_at: 1495795570,
        first_release_date: 1454025600,
        genres: ["Indie"],
        name: "Perraw-FPSCloneWar",
        platforms: ["PC (Microsoft Windows)"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/dcs03jqnid5xyk8iyrti.jpg", "images.igdb.com/igdb/image/upload/t_thumb/z84fxzjon9hbiqwwuubv.jpg", "images.igdb.com/igdb/image/upload/t_thumb/fdxe03mtinjx3sdejjuw.jpg"],
        summary: "PerrawisaFPSmultiplayer/TowerDefenseplacedinanfuturisticenvironmentDevelopedinfreetimeasahobby.WARNING:THISGAMEISEARLYACCESSALPHA.",
        url: "https://www.igdb.com/games/perraw-fps-clone-war",
    },
    {
        game_id: 13,
        id: 74857,
        created_at: 1508457600,
        first_release_date: 1512086400,
        genres: ["Platform", "Puzzle", "Role-playing (RPG)", "Adventure", "Indie"],
        name: "Transcend",
        platforms: ["PC (Microsoft Windows)"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/lrgn3fa3bbzaglnbf3mi.jpg", "images.igdb.com/igdb/image/upload/t_thumb/vfbyyaoqy3qbwreaynjz.jpg", "images.igdb.com/igdb/image/upload/t_thumb/wwxaqvlulmgbx2o8vzqy.jpg"],
        summary: "Apuzzleplatformerinwhichyoutranscendlifeanddeathtoreachyourgoals.",
        url: "https://www.igdb.com/games/transcend",
    },
    {
        game_id: 14,
        id: 78193,
        created_at: 1513468800,
        first_release_date: 1041292800,
        genres: ["Racing"],
        name: "TestDrive",
        platforms: ["PC (Microsoft Windows)", "PlayStation 2", "Xbox"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/sc75up.jpg", "images.igdb.com/igdb/image/upload/t_thumb/sc75uq.jpg", "images.igdb.com/igdb/image/upload/t_thumb/sc75ur.jpg"],
        summary:
            'TestDriveisaracinggamedevelopedbyPitbullSyndicate.InTestDrive,youplayasDennisBlack,astreetracerwhoiscontactedbyawheelchair-boundmanandhiredtoraceinhisplaceinaseriesofundergroundstreetracesknownas"testdrives".\n\nThiseditionofTestDrivehassomeimprovementsoverit\'spredecessor,TestDrive6.Thistimearoundthereisastorydrivenmode,called"TheUnderground."YoutaketheroleofDennisBlack,anindependentstreetracerwhoimproveshisstandingintheundergroundstreetracingworldwiththehelpofamysteriousbenefactor.',
        url: "https://www.igdb.com/games/test-drive--1",
    },
    {
        game_id: 15,
        id: 74958,
        created_at: 1508976000,
        first_release_date: 1509494400,
        genres: ["Simulator", "Strategy"],
        name: "ALVAROK",
        platforms: ["PC (Microsoft Windows)"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/wi3wkdfvqfkms4eqcr2y.jpg", "images.igdb.com/igdb/image/upload/t_thumb/srwhkpmyh9ribzsu6y7n.jpg", "images.igdb.com/igdb/image/upload/t_thumb/mzfrsvchncmyfwxediqc.jpg"],
        summary: "JapaneseIndiedeveloperStudioGIWisbackwithALVAROK,afunandeasy-to-playTacticalDefensegame.Playlocallywithfriendsorhoneyourskillsagainstthecomputerwithitsbuilt-indeeplearningAIsystem.Adaptandstrategize,utilizeyourvarioustroopstodefendandattacksimultaneously.",
        url: "https://www.igdb.com/games/alvarok",
    },
    {
        game_id: 16,
        id: 75076,
        created_at: 1509098229,
        first_release_date: 1538611200,
        genres: ["Racing", "Sport", "Indie", "Arcade"],
        name: "PartyCrashers",
        platforms: ["PC (Microsoft Windows)", "PlayStation 4", "Nintendo Switch"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/iifhzkrmhesfbsl6jpzb.jpg", "images.igdb.com/igdb/image/upload/t_thumb/sqcp9y1hm58jivdcetds.jpg", "images.igdb.com/igdb/image/upload/t_thumb/jxmvrbvxfpejyca860zd.jpg"],
        summary:
            'PartyCrashersisanarcadecombatracer,featuringfast-pacedlast-car-standinggameplay,withahugearrayofcustomisationoptionstoallowplayerstocreateyourownstyleofplay.\n\nBydefault,playersraceonasinglescreenandplayersthatfalltoofarbehindorfallofthetrackareeliminated.Thegameismademorehecticandroundsarekeptshortbyweaponsscatteredaroundthetrackthatcreatewaysforplayerstoeliminateeachother.Pointsareawardedforstayingaliveaslongaspossible.\n\nFollowinginthefootstepsofPartyGolf,thegamehasadeepcustomisationsystemthatallowseverythingabout"normal"gameplaytobechangedsoplayerscancreatewhateverstyleofgameplaytheylikethemost!',
        url: "https://www.igdb.com/games/party-crashers",
    },
    {
        game_id: 17,
        id: 74426,
        created_at: 1508117337,
        first_release_date: 978220800,
        genres: ["Platform"],
        name: "TheEmperor'sNewGroove",
        platforms: ["Game Boy Color"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/sc9kny.jpg", "images.igdb.com/igdb/image/upload/t_thumb/exalhrvzsqtdwg39ttwk.jpg", "images.igdb.com/igdb/image/upload/t_thumb/fh7pqmeogwp9nllj27cx.jpg"],
        summary: "TheEmperor'sNewGrooveisavideogamebasedonthe2000Disneyfilmofthesamename,developedbySandboxStudiosfortheGameBoyColor.",
        url: "https://www.igdb.com/games/the-emperors-new-groove--1",
    },
    {
        game_id: 18,
        id: 74369,
        created_at: 1507813635,
        first_release_date: 1517443200,
        genres: ["Simulator", "Strategy", "Indie"],
        name: "StartupFreak",
        platforms: ["PC (Microsoft Windows)"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/d9ocripwckm3rldaxijx.jpg", "images.igdb.com/igdb/image/upload/t_thumb/zx9wrgwml5qgk5vd3udm.jpg", "images.igdb.com/igdb/image/upload/t_thumb/oilrila2luf9poyrtxh8.jpg"],
        summary: "InStartupFreakyoutaketheroleofabuddingentrepreneur,andgrowyourveryownsoftwarestartupfromhumblebeginningstoamulti-milliondollarcompany.Alongthewayyouwillhavetoovercomecountlesschallenges.Buttheultimatequestionyoumustanswer:areyouaStartupFreak?",
        url: "https://www.igdb.com/games/startup-freak",
    },
    {
        game_id: 19,
        id: 79587,
        created_at: 1514505600,
        first_release_date: 539136000,
        genres: ["Platform", "Strategy", "Arcade"],
        name: "Subnodule",
        platforms: ["Mac"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/n5lfib14zsif7iojl01c.jpg", "images.igdb.com/igdb/image/upload/t_thumb/xrl6jy3fyycvti0a6wzk.jpg", "images.igdb.com/igdb/image/upload/t_thumb/bda3lj2q05jhxd851pit.jpg"],
        summary: "Youcontrolasubmarineinhostilewaters.Sharingthedeepseawithyouareseveraldangerouscreaturessuchasjellyfish,eels,sharksandthemysteriousX-Sub.Destroyeverythingtoreachthenextlevel.Thisgamehasintermissionsaswell.",
        url: "https://www.igdb.com/games/subnodule",
    },
    {
        game_id: 20,
        id: 86080,
        created_at: 1517529600,
        first_release_date: 1451520000,
        genres: ["Music"],
        name: "SingStar:Frozen",
        platforms: ["PlayStation 3", "PlayStation 4"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/sc7fxs.jpg", "images.igdb.com/igdb/image/upload/t_thumb/sc7fxr.jpg", "images.igdb.com/igdb/image/upload/t_thumb/sc7fxq.jpg"],
        summary:
            "SingStar:FrozenisakaraokegamebasedontheanimatedmovieFrozen.ExceptforthesongLetItGofromDemiLovato,whichistheavailableinalllanguageversion,theotherninesongsaretranslatedandtakendirectlyfromthemovie(includingdialogue).Therearenochangestothegameplayformula:player(s)singintoamicrophoneandthegamegivespointsbasedontheperformance.Itisonlyratedifthecorrectnotishitatthecorrecttime;thesungwordsoroctavedoesnotplayintotheresult.",
        url: "https://www.igdb.com/games/singstar-frozen",
    },
    {
        game_id: 21,
        id: 93800,
        created_at: 1521331200,
        first_release_date: 1522281600,
        genres: ["Simulator", "Adventure", "Indie"],
        name: "Temptation",
        platforms: ["PC (Microsoft Windows)"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/cmd5yfdl9kksjnnyoyuj.jpg", "images.igdb.com/igdb/image/upload/t_thumb/sngfz6kmc9ofedjpfysq.jpg", "images.igdb.com/igdb/image/upload/t_thumb/biwo0zlfx1j1hayewus9.jpg"],
        summary: "Temptation-agameaboutamedievalpriestwhoissuddenlypossessedbyademon.Yourgoalistoperformanunusualritualofexorcismtobanishthedemonfromhimself!",
        url: "https://www.igdb.com/games/temptation",
    },
    {
        game_id: 22,
        id: 81357,
        created_at: 1515801600,
        first_release_date: 1378252800,
        genres: ["Simulator"],
        name: "FarmingSimulator",
        platforms: ["PlayStation 3"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/us23glclxamzogyo48so.jpg", "images.igdb.com/igdb/image/upload/t_thumb/lyhbt09yull4mksdiw6c.jpg", "images.igdb.com/igdb/image/upload/t_thumb/q3fwaeqguzmhsgcyx6dq.jpg"],
        summary: "Discoverawide,agriculturalscenerywithfields,roads,yourfarmaswellasasmallvillage.Cultivateyourfieldswithvariousthreedimensionalvehiclesfoundinyourgenerousfleet-modeledafteroriginalmachinesandvehiclesbyprestigiousmanufacturers.",
        url: "https://www.igdb.com/games/farming-simulator",
    },
    {
        game_id: 23,
        id: 94804,
        created_at: 1521417600,
        first_release_date: 1592956800,
        genres: ["Simulator", "Strategy", "Indie"],
        name: "SpaceStationContinuum",
        platforms: ["PC (Microsoft Windows)"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/sxmocemxh7fdc8szw4y8.jpg", "images.igdb.com/igdb/image/upload/t_thumb/brcuacvrlpxtts5opltp.jpg", "images.igdb.com/igdb/image/upload/t_thumb/hrrtethoeszgwnaryqvi.jpg"],
        summary: "SpaceStationContinuumisabuilding&managementsiminspiredbythepast,present,andfutureofhumansinspace.",
        url: "https://www.igdb.com/games/space-station-continuum",
    },
    {
        game_id: 24,
        id: 80867,
        created_at: 1515369600,
        first_release_date: 725760000,
        genres: ["Shooter", "Arcade"],
        name: "NightRaid",
        platforms: ["PC DOS"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/sc75co.jpg", "images.igdb.com/igdb/image/upload/t_thumb/sc75cn.jpg", "images.igdb.com/igdb/image/upload/t_thumb/sc75cp.jpg"],
        summary:
            "Remakeof1982'sParatrooper.\n\nTheplayercontrolsagunturretatthebottomofthescreen.Theturretcanswiveltocoveralargeareaofthescreen,butcannotmovefromitsbase.Helicoptersflyacrossthescreenatvaryingheights,droppingparatroopers.Thegunmayfiremultipleshotsatonce,andtheshotsmaydestroyhelicoptersorshootparatroopers.Paratroopersmaybedisintegratedbyadirecthit,ortheirparachutesmaybeshot,inwhichcasetheywillplummettoearth(splatteringanddying,killinganyparatrooperontowhomtheyfall).Periodically,jetsmayflybyanddropbombs;thejetsandbombsmaybeshotaswell.",
        url: "https://www.igdb.com/games/night-raid--1",
    },
    {
        game_id: 25,
        id: 91231,
        created_at: 1521072000,
        first_release_date: 1489104000,
        genres: ["Simulator"],
        name: "StickmanDismounting",
        platforms: ["iOS"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/ljj41yqadl5sxhnq3h1o.jpg", "images.igdb.com/igdb/image/upload/t_thumb/myh8sbkte9r7i1oxnmow.jpg", "images.igdb.com/igdb/image/upload/t_thumb/boy4wxbuney7amnrblrs.jpg"],
        summary:
            "Performamazingstunts,crashintowalls,breakbones,destroyvehiclesandhavethefun!\n\nFEATURES:\n-uniqueactiveragdollphysicssystem\n-crunchysoundeffects\n-multiplelevels\n-multiplevehicles\n-multiplepropsforlevelcustomization\n-replaysystemwithsavingandsharingabilities\n\nDonotattemptgameactionsinreallife.",
        url: "https://www.igdb.com/games/stickman-dismounting",
    },
    {
        game_id: 26,
        id: 94567,
        created_at: 1521408228,
        first_release_date: 1131580800,
        genres: ["Simulator", 3],
        name: "PCFútbol2006",
        platforms: ["PC (Microsoft Windows)"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/sc935n.jpg", "images.igdb.com/igdb/image/upload/t_thumb/sc935m.jpg", "images.igdb.com/igdb/image/upload/t_thumb/sc935l.jpg"],
        summary: "PCFútbolisafootballmanagerialgamewithdifferentgamestyles.Youcantakeanequipfromthebeginningorplaythemanagermodewaitingandselectingoffersfromtheequips.\n\nYoucantradeandtrainplayers,makestrategics,buildthestadiumandservices,selectsponsors,sellmerchandisingandlotofmore.",
        url: "https://www.igdb.com/games/pc-futbol-2006",
    },
    {
        game_id: 27,
        id: 90228,
        created_at: 1520640000,
        first_release_date: 1367193600,
        genres: ["Adventure", "Indie"],
        name: "Skumring",
        platforms: ["PC (Microsoft Windows)"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/twpkqd6awodfg3ialsyl.jpg", "images.igdb.com/igdb/image/upload/t_thumb/i9fxn4fcyhlk9sqrmhzf.jpg", "images.igdb.com/igdb/image/upload/t_thumb/b8vwddfkr6zrwohzfzle.jpg"],
        summary:
            "PortHorizon1951.Acityonthevergeofcollapse.Moralcollapse.Crime.Corruption.Greed...Money.PrivateeyeCooperChutneythoughthewastheexception.Whenabeautifuldameindistressentershisofficeheisreadytoshowthatsomeonestillcaresaboutsomethinginthiswretchedtown.ButashesoonwilllearneverythingcanchangeduringacoldPortHorizonnight...Skumringªfeatures30+locations,15+charactersand40+inventoryitems.Itwillalsofeatureavariedsoundtrack,consistingoftraditionaljazzandoriginalinterpretationsofclassicalmusic.",
        url: "https://www.igdb.com/games/skumring",
    },
    {
        game_id: 28,
        id: 146815,
        created_at: 1620325446,
        first_release_date: 1230681600,
        genres: ["Puzzle"],
        name: "ParkingLotMaze",
        platforms: ["PC (Microsoft Windows)"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/sc9gxx.jpg", "images.igdb.com/igdb/image/upload/t_thumb/sc9gxw.jpg", "images.igdb.com/igdb/image/upload/t_thumb/sc9gxv.jpg"],
        summary: "ParkingLotMazeisapuzzlegamewhereasaparkinglotmanager,youneedtofreecarsfromgridlockbeforethestresslevelhitstheroof.",
        url: "https://www.igdb.com/games/parking-lot-maze",
    },
    {
        game_id: 29,
        id: 148226,
        created_at: 1621464692,
        first_release_date: 1621468800,
        genres: ["Adventure", "Indie"],
        name: "IfItPleasetheCourt",
        platforms: ["Linux", "PC (Microsoft Windows)", "Mac"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/sc9o8w.jpg", "images.igdb.com/igdb/image/upload/t_thumb/sc9o8x.jpg", "images.igdb.com/igdb/image/upload/t_thumb/sc9o8y.jpg"],
        summary: "Atext-basedinteractivelesbianromancenovelsetin1700'sFrance.Gatherintel,orgambleonloveinVersailles!Whowillcatchyoureye:aspymistress,apoet,oratraitortotheking?",
        url: "https://www.igdb.com/games/if-it-please-the-court",
    },
    {
        game_id: 30,
        id: 132734,
        created_at: 1587643768,
        first_release_date: 1640908800,
        genres: ["Strategy", "Indie"],
        name: "IronVulture",
        platforms: ["PC (Microsoft Windows)"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/sc8t1b.jpg", "images.igdb.com/igdb/image/upload/t_thumb/sc8t1c.jpg", "images.igdb.com/igdb/image/upload/t_thumb/sc8t1e.jpg"],
        summary: "IronVultureisareal-timestrategylinedefender.Youcancommandsixsoldiersinreal-timecombat,movethemacrosslanes,andusetheirabilitiestoeliminatewaveafterwaveofmutatedcreatures.",
        url: "https://www.igdb.com/games/iron-vulture",
    },
    {
        game_id: 31,
        id: 143104,
        created_at: 1612324563,
        first_release_date: 1611273600,
        genres: ["Indie"],
        name: "iamstillhere.",
        platforms: ["Web browser"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/sc90ix.jpg"],
        summary: "Ashortexperienceaboutghostsandplacesandpeople,setinthefirstdays/weeksafterthelockdownendedinMelbourne.",
        url: "https://www.igdb.com/games/i-am-still-here",
    },
    {
        game_id: 32,
        id: 105595,
        created_at: 1532106731,
        first_release_date: 1532649600,
        genres: ["Indie"],
        name: "MagicMechsuitAkane",
        platforms: ["PC (Microsoft Windows)"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/amnz8ix1w57zhcou4ftm.jpg", "images.igdb.com/igdb/image/upload/t_thumb/nzulu2ckee51i9y6jjc3.jpg", "images.igdb.com/igdb/image/upload/t_thumb/wdmm3ctazrdx81isv1eg.jpg"],
        summary:
            'MagicMechSuitAkane\n"Mechanism-replacementactionshooting"-start\nCombatactiontocreateapoweredsuitbycombiningupto16partssuchasgeneratorsandradiators!\nInadditiontobeingabletoplayofflinewithapresetmachineorself-mademachinewith1VS1,youcanalsoplayonlinewithupto3VS3.\nDefeatyouropponentwithametalcalledMechSuitandarmorthatmagicgottogether!',
        url: "https://www.igdb.com/games/magic-mechsuit-akane",
    },
    {
        game_id: 33,
        id: 122050,
        created_at: 1566892004,
        first_release_date: 1640908800,
        genres: ["Platform", "Puzzle", "Adventure", "Indie"],
        name: "AJuggler'sTale",
        platforms: ["PC (Microsoft Windows)", "PlayStation 4", "Xbox One", "Nintendo Switch"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/sc6wq3.jpg", "images.igdb.com/igdb/image/upload/t_thumb/sc6wq5.jpg", "images.igdb.com/igdb/image/upload/t_thumb/sc6wq4.jpg"],
        summary: "LeadAbbythestringpuppetthroughabruised,butbeautifulworldinthispoetic3Dadventure.Solveriddles,evadetraps,andshakeoffpursuersonyourwaytofindfreedom.CanAbbytakecontrolofherownfateandmakeadifferencewithallthestringsattached?",
        url: "https://www.igdb.com/games/a-jugglers-tale",
    },
    {
        game_id: 34,
        id: 130974,
        created_at: 1582462146,
        first_release_date: 1575590400,
        genres: ["Strategy", "Indie"],
        name: "DodgeIfyouCan!",
        platforms: ["PC (Microsoft Windows)"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/sc85wc.jpg", "images.igdb.com/igdb/image/upload/t_thumb/sc85we.jpg", "images.igdb.com/igdb/image/upload/t_thumb/sc85wf.jpg"],
        summary: "DodgeIfyouCan!AsimplegamewhereyouwilleitheremergeasaMasterofstrategy,orbecomeastatistic.Willyourstrategyandwitsprevailamongthestormofbullets?Willyougodownasalegend?Onlyyoucandecide.Now-Dodge,IfyouCan!",
        url: "https://www.igdb.com/games/dodge-if-you-can",
    },
    {
        game_id: 35,
        id: 108661,
        created_at: 1536219841,
        first_release_date: 1537142400,
        genres: ["Adventure", "Indie"],
        name: "EscapefromthePrincess",
        platforms: ["PC (Microsoft Windows)"],
        screenshots: ["images.igdb.com/igdb/image/upload/t_thumb/kq3jon9oz2stetpbhi5j.jpg", "images.igdb.com/igdb/image/upload/t_thumb/jkx6biyilxhlf04zuxdd.jpg", "images.igdb.com/igdb/image/upload/t_thumb/zyatdy7donfliviw4tbn.jpg"],
        summary: "Rosettadreamsofbecomingamagician,butsheisn'tcutoutforit.Fatebringshertogetherwithamysteriouswitch,whoispursuedbytheprincessherself.ThewitchpromisestomakeRosettaamagicianinreturnforherhelp.ButRosefallsinlovewithawitchwhoisclearlyhidingsomething.",
        url: "https://www.igdb.com/games/escape-from-the-princess",
    },
];
